### PR TITLE
Remove bar if no company #58

### LINKED ISSUE #58: Remove bar if no company
This list is already coming from an array, but we need to extend this:

- if array empty remove the bar all-together from the UI.
- the array should contain objects with:
  - url to IMG with extension
  - string for the alt and title tag
  - images should have a fixed height so when new logos are added they will be in the same proportion even if the fiels will be all over the place, like raster mixed with vector.

Screen Shot 2020-11-18 at 10 14 20 AM

### PR DESCRIPTION
**Pull request by edhenderson**
- extends brands data to `url`, `alt` and `title`
- use `img` tag in template rather than `include` as they could be raster in the future
- closes #58

### CODE REVIEW

**Comment by edhenderson** [comment]
@davidgatti Good for a look 🏓

**Review by davidgatti — CHANGES_REQUESTED** [review]
The logo now are black, not white, not good :)

**Comment by edhenderson** [comment]
The logos are uncoloured in the SVG so they appear black. I'll tweak them white.

**Comment by edhenderson** [comment]
@davidgatti Good for another look 🏓

**Pull request merged**
