### PR TITLE
Titles #86

### LINKED ISSUE #86: Titles
This is how is should be:

- home page `name fo the page` (example: `OpenVPN Access Server - Unlimited Connected Devices`)
- demo `demo - short name` (example: `Demo - OpenVPN Access Server`)
- etc.

### PR DESCRIPTION
**Pull request by edhenderson**
- add flag `isHome` to home page
- better title
- closes #86

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
This PR is not even close to the Issue that I have created, i'm confused.

**Comment by edhenderson** [comment]
@davidgatti Would you be able to expand the explanation of the issue with some more details? I am confused as to what you are asking then if you aren't referring to the `<title>`s. Thanks.

**Comment by edhenderson** [comment]
@davidgatti What page do you see `- 0x4447`?

**Comment by davidgatti** [comment]
On the home page, @edhenderson I don't want to spend 30 min to explain how I want a title, I'm sorry to be harsh here but I'm frustrated, if you believe the issues that I created is unclear, I understand and I have no idea how else to explain the idea of well structured titles. And if this is the case we can close this PR.

**Comment by edhenderson** [comment]
Screenshot 2020-11-23 at 11 04 11

This is strange. On the home page I see this ^

The `TODO` is coming from `_config.yml`:

```
description: TODO
```

Did you restart your jekyll server to pick up config changes?

**Comment by davidgatti** [comment]
Hmm strange I see something else. OK, will check later what is going on, maybe the branch switch did not rebuild the site correctly.

**Comment by edhenderson** [comment]
If you change branches and there are `config.yaml` changes, you need to restart the server. In fact if you change `config.yaml` at all, you need to restart (or start) the server.

**Comment by davidgatti** [comment]
Yes starting from scratch made it work, but we are still not there, will make a video and will ty to explain how the titles should be this way.

**Comment by edhenderson** [comment]
OK, thanks!

**Comment by edhenderson** [comment]
@davidgatti Good for another look 🏓

**Review by davidgatti — CHANGES_REQUESTED** [review]
I don't see this working.

Screen Shot 2020-11-27 at 9 59 22 AM

**Comment by edhenderson** [comment]
@davidgatti Did you stop and start the Jekyll server?

**Comment by edhenderson** [comment]
Screenshot 2020-11-27 at 14 05 21
Screenshot 2020-11-27 at 14 05 04

**Pull request merged**
