### PR TITLE
Add .html extension #65

### LINKED ISSUE #65: Add .html extension
I'd like to have all the sub pages that are on the page have a `.html` extension, for example: error, thank you, and whatever else is there.

### PR DESCRIPTION
**Pull request by edhenderson**
- closes #65

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
Thank you has the HTML, but `http://localhost:4000/schedule_demo/` dose not.

**Comment by edhenderson** [comment]
I set that to:

```
permalink: /schedule_demo.html
```

What would you like the URL of that page to be?

**Comment by davidgatti** [comment]
like this `http://localhost:4000/schedule_demo.html`

**Comment by edhenderson** [comment]
Aha, I see. The permalink was set correctly but there was a rogue `href`, thanks.

**Comment by edhenderson** [comment]
@davidgatti Good for another look.

**Review by davidgatti — APPROVED** [review]

**Pull request merged**
