### PR TITLE
Sitemap

### PR DESCRIPTION
**Pull request by vosaul**
image

#19

### CODE REVIEW

**Comment by davidgatti** [comment]
@vosaul do you think this URLs are usefull for Google? 

```
<url>
<loc>http://localhost:4000/assets/libs/flickity-fade/sandbox/basic.html</loc>
<lastmod>2020-09-19T08:36:58+02:00</lastmod>
</url>
<url>
<loc>http://localhost:4000/assets/libs/imagesloaded/sandbox/background/</loc>
<lastmod>2020-09-19T08:36:58+02:00</lastmod>
</url>
<url>
<loc>http://localhost:4000/assets/libs/imagesloaded/sandbox/progress/</loc>
<lastmod>2020-09-19T08:36:58+02:00</lastmod>
</url>
<url>
<loc>http://localhost:4000/assets/libs/typed.js/</loc>
<lastmod>2020-09-19T08:36:58+02:00</lastmod>
</url>
```

**Comment by vosaul** [comment]
Yes, this is a standard sitemap for search engines.

**Comment by davidgatti** [comment]
I understand, but I don't think the .js included file have anything meaningful for the user. Or do you think when you visit those sites, that there is something relevant?

**Comment by vosaul** [comment]
Is that okay? I also excluded demo.html
image

**Comment by davidgatti** [comment]
I don't understand you logic ;) so adding some .js file is OK, but linking to pages that we want to show users is bad?

**Comment by vosaul** [comment]
fixed

**Pull request merged**
