### PR TITLE
Add Robot txt

### PR DESCRIPTION
**Pull request by vosaul**
Added Robot.txt #18

### CODE REVIEW

**Comment by davidgatti** [comment]
@vosaul so you have set

```
User-agent: * 
Disallow: /
```

So you want for any crawler not to index any page on the site?

**Comment by vosaul** [comment]
Yes, in development mode, I wouldn't want scanners to index pages. This is easy to edit before being released into production.

**Comment by davidgatti** [comment]
I won't be deploying a development version, only production. Please make it so that crawlers have a full access.

**Comment by vosaul** [comment]
allowed all

**Review by davidgatti — APPROVED** [review]

**Pull request merged**
