### PR TITLE
Switch positions #85

### LINKED ISSUE #85: Switch positions
Screen Shot 2020-11-22 at 9 52 44 AM

### PR DESCRIPTION
**Pull request by edhenderson**
- closes #85

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
I'm unhappy with this PR, because the layout is all visually wrong, yes you did switch positions, but the layout section is now incorrect. the layout is interlaced between gray and white, and how there are 2 white sections and one gray. It be nice if in the future I don't have to pay attention for things like this.

**Comment by edhenderson** [comment]
@davidgatti I think I understand what you are saying. You'd like the *contents* of the sections to be switched, not the actual sections?

**Comment by davidgatti** [comment]
Yes

**Comment by edhenderson** [comment]
@davidgatti Good for another look 🏓

**Pull request merged**
