### PR TITLE
Support button #97

### LINKED ISSUE #97: Support button
Add a button that links to here: https://support.0x4447.com/ Same button style as the one in the beginning of the page. Or any variant that will look good in there.

Screen Shot 2020-12-04 at 9 43 20 AM

### PR DESCRIPTION
**Pull request by edhenderson**
- closes #97

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
That button brakes the look of that section. Lets link this text to the support page `We'll be there to lend a helping hand.`

**Comment by edhenderson** [comment]
🏓

**Comment by davidgatti** [comment]
@edhenderson make the URL color aqua, the same color that the `will help you with anything` text is painted with.

**Comment by edhenderson** [comment]
🏓

**Review by davidgatti — APPROVED** [review]

**Pull request merged**
