### PR TITLE
edited brands svg, yml, html - added title tags

### PR DESCRIPTION
**Pull request by vosaul**
Here used SVG files, so alt attributes no need.
I edited all brands SVG files -moved <svg> tags from SVG files into brand.html and added <title> attribute and added titles in the brand.yml
If you add new brands in the future, you will need to remove tags `<svg> and </svg>` in the SVG files 
image
image
#9

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
- do not edit the SVGs keep them as they are, those assets are not to be chagned.
- And when I mentioned about `alt` and `title`, I ment here: `GE Predix Platform: Using AWS Elasticache with Open Service Broker`

**Comment by vosaul** [comment]
image
image

What other files could I think of? I haven't come up with another way to add a title tag for readers to SVG files. We can display SVG as IMG, but then we will not be able to control SVG properties (color for example)

**Comment by vosaul** [comment]
Or do you mean to add more informative alt and title to all pictures (not brands)?
Is the text individual in each picture or something in common (the title of the article, section, etc.)?

**Comment by vosaul** [comment]
Somehow? Add matching keys to all images? Link to site / page / section attributes or does everything have to be filled in manually?
image

**Comment by davidgatti** [comment]
OK, for now lets forget about this.

**Pull request closed without merging**
