### PR TITLE
Add arrow in the first section #84

### LINKED ISSUE #84: Add arrow in the first section
Add this arrow in the first section, and when someone clicks on it, it scrolls down to the next section.

Screen Shot 2020-11-21 at 9 38 50 AM
Screen Shot 2020-11-22 at 9 40 35 AM

### PR DESCRIPTION
**Pull request by edhenderson**
- closes #84

### CODE REVIEW

**Comment by edhenderson** [comment]
I have configured this the best I can. In the example page you gave me, https://landkit.goodthemes.co/enterprise.html the arrow appears at the bottom of a symmetrical curve so sits nicely. The curve here is a little more slanted so its a little harder to get right.

**Review by davidgatti — CHANGES_REQUESTED** [review]
Is it possible to have the button going in the middle of the line? Right now it looks like you dropped it there by mistake.

**Comment by edhenderson** [comment]
@davidgatti If you see my comment above for an explanation. The arrow has no knowledge of the curve.

In the template, it is a symmetrical curve (u-shape) so the bottom of the curve is known. With this curve, its harder to predict where the bottom of the curve will be. I spent ages checking all the dimensions / screen sizes and this is the best I can do with the template.

My professional opinion would be to either remove the arrow, or change the curve to the u-shaped.

Let me know what you want to do?

**Comment by davidgatti** [comment]
I see, OK, in this case I will skip this feature for now. Thank you for the explaantion.

**Pull request closed without merging**
