### PR TITLE
Fix blurry image

### PR DESCRIPTION
**Pull request by x5hwuk7nc6jsudcc**

### CODE REVIEW

**Comment by davidgatti** [comment]
Before we finish I'd like to revisit this PR and see if we can fix the issue with the image. Could you reorgaznie the image resolutions so they all have a good size so they are not massive and yet will look ok on most monitors, while making them sharp?

**Comment by x5hwuk7nc6jsudcc** [comment]
Hey @davidgatti
Yep I can re-size these.  It's best if I work with the original image though rather than an copy that is already resized/compressed.  Can you send these (or upload into repo)?

**Comment by davidgatti** [comment]
@x5hwuk7nc6jsudcc  there you go: [PNG.zip](https://github.com/0x4447-office/0x4447_template_office_jekyll/files/6389658/PNG.zip)

**Comment by x5hwuk7nc6jsudcc** [comment]
Do you want to try that @davidgatti?  That's re-saved at 2x the display resolution and re-compressed.

**Comment by davidgatti** [comment]
I still see it blurry, but if I open the image itself it looks good. I have a 1080p screen so you knwo.

**Comment by x5hwuk7nc6jsudcc** [comment]
Hey @davidgatti just checking the zip you sent me above looks like the images were in PNG format.  Is this the original format?  I think you said they were originally scans of hand-drawn images? If so, can you send them to me in the original format that the scanner produced (pdf/jpg/tiff) OR ideally if they were 'hand-drawn' in a vector application, the original vector image (eps/svg/etc).

**Comment by davidgatti** [comment]
@x5hwuk7nc6jsudcc they were hand drown on a iPad :) This are the "original" despite being digital. Anyway, I think we can call it a day, and in the future I will try to figure this one out.

**Pull request merged**
