### PR TITLE
Vs/#25 changes to the demo page

### PR DESCRIPTION
**Pull request by vosaul**
#25

### CODE REVIEW

**Comment by davidgatti** [comment]
I had an idea how to make the page better. as you can see I want you to remove the side image, center the form on the page, and then rearange the input fields a bit. The header of the page stays the same. 

Screen Shot 2020-10-01 at 9 29 06 AM
Screen Shot 2020-10-01 at 9 30 21 AM

**Comment by vosaul** [comment]
Done,
the order of the fields is somewhat different, it seems more logical to me.
But if you disagree I will change it
image

**Comment by davidgatti** [comment]
Yes please change, I don't do thinks at random.

**Comment by vosaul** [comment]
changed

**Pull request merged**
