### PR TITLE
jekyll init

### PR DESCRIPTION
**Pull request by vosaul**
Jekyll structure created and converted the home page and parts -  footer, navigation, etc. 
#1

### CODE REVIEW

**Comment by davidgatti** [comment]
OK, there was some bad communication on my part. The original issue was very unclear, and the key part was hidden at the end of the message. So let me try one more time to explain what I need.

- the provided ZIP with the template has a lot of templates for different type of pages. I did send you the whole thing, because that is the package that I received, but it dose not mean I want to use all of them. I just want to use one template
- https://landkit.goodthemes.co/desktop-app.html this is the page that I'm interested in.
- This mean this work should not take more then 1h, if you are going to work for over 1h it means there is something wrong with what you are doing and you should stop and ask for additional questions.
- The page `desktop-app.html` is a single page, there are no other pages that needs to be done. you have to just copy the HTML that this page has, and brake it down in a way that makes sense for Jekyll to them manage and work with.
- Forget about what I wrote in the original message, don't do any extra - just brake the template down, and after this I will check your work, and make sure you are doing what I want.

**Comment by vosaul** [comment]
I realized.
desktop-app.html already converted. I'll polish it. 
Do I have to create a commit with only one template? (without other already converted pages)

**Comment by davidgatti** [comment]
@vosaul yes, please remove everything else and keep just this one page.

**Comment by vosaul** [comment]
ok

**Comment by vosaul** [comment]
removed extra pages and data files and added SEO tags to the head section

**Comment by davidgatti** [comment]
The Support section is off, the text spills over the predefined constrains, compare the live version with your's.

**Comment by vosaul** [comment]
I have reviewed and do not see the bugs you wrote about. You must have seen some previous commit

I noticed a difference in the paddings  here:

image

And text colors difference here:
image

and fixed it

**Comment by davidgatti** [comment]
Screen Shot 2020-09-08 at 11 45 27 AM

This is what I see.

**Comment by vosaul** [comment]
I'm sorry, it's probably time for me to change my glasses  :(
Fixed

**Comment by davidgatti** [comment]
OK :) no problem.

**Pull request merged**
