### PR TITLE
Custom URL to review #100

### LINKED ISSUE #100: Custom URL to review
Allow the ability to add a custom URL for both selected sections.

Screen Shot 2020-12-04 at 10 10 25 AM

### PR DESCRIPTION
**Pull request by edhenderson**
- demo link added to first testimonial (to show difference in functionality)
- template checks for optional link, if it exists, render it, otherwise, render text
- closes #100

### CODE REVIEW

**Comment by davidgatti** [comment]
@edhenderson yes, this is what I wanted.

**Comment by edhenderson** [comment]
Hurrah, then I'm happy if you want to merge!

**Comment by edhenderson** [comment]
🏓

**Comment by davidgatti** [comment]
@edhenderson well I don't want just one side to have the URL I need one ULR per review.

**Comment by edhenderson** [comment]
@davidgatti Thats just me showing you that it renders if there isn't a url. Can easy add another URL.

**Review by davidgatti — APPROVED** [review]

**Comment by edhenderson** [comment]
🏓

**Pull request merged**
